### PR TITLE
Fix syntax error in Puzzle #4

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Closing this :-)

**Comment by callahad** [comment]
Hah! Thanks. I'm _really_ bad at watching my GitHub notifications. Only seeing this five months later.

<3

**Comment by kamalmarhubi** [comment]
no worries :-)

**Comment by callahad** [comment]
You just had to rub it in that you _do_ watch your notifications, didn't you?

**Comment by kamalmarhubi** [comment]
You know how it is... got to stay on top of all the important things I'm doing.

**Pull request closed without merging**
